// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhvpDB8noqgvPe1lBHrNPrt3TnA5w6uJI',
    appId: '1:290689363529:web:69bf126fed7a9526585998',
    messagingSenderId: '290689363529',
    projectId: 'zoom-clone-e2887',
    authDomain: 'zoom-clone-e2887.firebaseapp.com',
    storageBucket: 'zoom-clone-e2887.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-pjpOcOkN1ya822PgwbfDPF16RyBESI',
    appId: '1:290689363529:android:9bd64a99e5ff8aba585998',
    messagingSenderId: '290689363529',
    projectId: 'zoom-clone-e2887',
    storageBucket: 'zoom-clone-e2887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZz3n24uyiuEKv1izuaBRElANvu2Tc2Q',
    appId: '1:290689363529:ios:14cfcc580e731bbf585998',
    messagingSenderId: '290689363529',
    projectId: 'zoom-clone-e2887',
    storageBucket: 'zoom-clone-e2887.appspot.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZz3n24uyiuEKv1izuaBRElANvu2Tc2Q',
    appId: '1:290689363529:ios:aaa75e164cfa775a585998',
    messagingSenderId: '290689363529',
    projectId: 'zoom-clone-e2887',
    storageBucket: 'zoom-clone-e2887.appspot.com',
    iosBundleId: 'com.example.zoomClone.RunnerTests',
  );
}
